steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/solar-haven-446021-j1/flask-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/solar-haven-446021-j1/flask-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'flask-app',
           '--image', 'gcr.io/solar-haven-446021-j1/flask-app',
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated']

images:
  - 'gcr.io/solar-haven-446021-j1/flask-app'